export const SELECT_LOCATION = "SELECT_LOCATION";
export const CLEAR_LOCATION = "CLEAR_LOCATION";
export const FORM_COMPLETION_ERROR = "FORM_COMPLETION_ERROR";
export const PLACES_SEARCH_LOADING = "PLACES_SEARCH_LOADING";
export const PLACES_SEARCH_COMPLETE = "PLACES_SEARCH_COMPLETE";
export const PLACES_SEARCH_ERROR = "PLACES_SEARCH_ERROR";
export const METERS = "METERS";
export const MILES = "MILES";
